#!/usr/bin/env ruby

# The sequence of triangle numbers is generated by adding the natural numbers. So 
# the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten 
# terms would be:
# 
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# 
# Let us list the factors of the first seven triangle numbers:
# 
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# 
# What is the value of the first triangle number to have over five hundred divisors?

def factors(num)
  factors = []
  (1..Math.sqrt(num)).each do |i|
    factors << i if num % i == 0
  end
  factors
end

n, nth_triangle_number, num_triangle_factors = 0, 0, 0
while num_triangle_factors <= 500
  nth_triangle_number += n
  num_triangle_factors = 2*factors(nth_triangle_number).length

  n += 1
end

p nth_triangle_number